## Data read

In [218]:
import numpy as np
from class_trial import StockData

In [484]:
# 069500	KODEX 200 \
# 229200	KODEX 코스닥150 \ Kosdaq Composite Index (^KQ11)
# 133690	TIGER 미국나스닥100 \ 
# 143850	TIGER 미국S&P500선물(H) \# 379800	KODEX 미국S&P500TR \
# 114260	KODEX 국고채3년 \
# 153130	KODEX 단기채권 \
# 157450	TIGER 단기통안채\ # 357870	TIGER CD금리투자KIS(합성) \
# Dow Jones Industrial Average (^DJI)

tic = ["069500.KS", "229200.KS",
             "133690.KS", "143850.KS",
             "114260.KS", "153130.KS",
             "157450.KS"
             ]

# tic = ["069500.KS", "^KQ11",
#              "133690.KS", "143850.KS",
#              "114260.KS", "153130.KS",
#              "157450.KS",
#              ]
stock_data = StockData(tic)

In [563]:
data = stock_data.download_data('2022-6-1', '2024-2-27','1d')

c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[                       0%%                      ]c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  7 of 7 completed

In [564]:
data.Close.dropna(thresh = 6)

Ticker,069500.KS,114260.KS,133690.KS,143850.KS,153130.KS,157450.KS,229200.KS
Date,,,,,,,
2022-06-02,35055.0,56280.0,70340.0,48185.0,103440.0,100875.0,12395.0
2022-06-03,35250.0,56300.0,71650.0,49130.0,103455.0,100890.0,12350.0
2022-06-07,34595.0,56125.0,70455.0,48190.0,103455.0,100880.0,12005.0
2022-06-08,34670.0,56125.0,71075.0,48775.0,103455.0,100890.0,12035.0
2022-06-09,34565.0,56170.0,70735.0,48270.0,103470.0,100920.0,12155.0
...,...,...,...,...,...,...,...
2024-02-20,35875.0,59175.0,105305.0,55890.0,108740.0,106120.0,13645.0
2024-02-21,35795.0,59185.0,104190.0,55605.0,108745.0,106135.0,13665.0
2024-02-22,35980.0,59300.0,105170.0,56170.0,108795.0,106160.0,13765.0
2024-02-23,36090.0,59230.0,106825.0,56950.0,108790.0,106170.0,13805.0
2024-02-26,35800.0,59330.0,106300.0,56790.0,108810.0,106180.0,13880.0

In [565]:
df,ret = stock_data.clean()

In [566]:
ret

Ticker,069500.KS,114260.KS,133690.KS,143850.KS,153130.KS,157450.KS,229200.KS
Date,,,,,,,
2022-06-02,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2022-06-03,1.005563,1.000355,1.018624,1.019612,1.000145,1.000149,0.996370
2022-06-07,0.981418,0.996892,0.983322,0.980867,1.000000,0.999901,0.972065
2022-06-08,1.002168,1.000000,1.008800,1.012139,1.000000,1.000099,1.002499
2022-06-09,0.996971,1.000802,0.995216,0.989646,1.000145,1.000297,1.009971
...,...,...,...,...,...,...,...
2024-02-20,0.988292,0.999831,0.997679,0.996879,1.000046,1.000000,1.007755
2024-02-21,0.997770,1.000169,0.989412,0.994901,1.000046,1.000141,1.001466
2024-02-22,1.005168,1.001943,1.009406,1.010161,1.000460,1.000236,1.007318
2024-02-23,1.003057,0.998820,1.015736,1.013886,0.999954,1.000094,1.002906
2024-02-26,0.991965,1.001688,0.995085,0.997191,1.000184,1.000094,1.005433

In [556]:
df

Ticker,Date,end of month,year,month,069500.KS,114260.KS,133690.KS,143850.KS,153130.KS,157450.KS,229200.KS
0,2023-03-02,True,2023,3,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,2023-03-03,True,2023,3,1.002189,1.002831,1.001287,1.010202,1.000048,1.000097,1.028838
2,2023-03-06,True,2023,3,1.014038,1.000176,1.020714,1.019003,1.000285,1.000097,1.023717
3,2023-03-07,True,2023,3,0.994770,1.002910,1.003499,1.000639,1.000238,1.000146,0.998736
4,2023-03-08,True,2023,3,0.985774,0.996395,1.000488,0.982961,1.000000,1.000146,1.001265
...,...,...,...,...,...,...,...,...,...,...,...
222,2024-02-20,True,2024,2,0.988292,0.999831,0.997679,0.996879,1.000046,1.000000,1.007755
223,2024-02-21,True,2024,2,0.997770,1.000169,0.989412,0.994901,1.000046,1.000141,1.001466
224,2024-02-22,True,2024,2,1.005168,1.001943,1.009406,1.010161,1.000460,1.000236,1.007318
225,2024-02-23,True,2024,2,1.003057,0.998820,1.015736,1.013886,0.999954,1.000094,1.002906
226,2024-02-26,True,2024,2,0.991965,1.001688,0.995085,0.997191,1.000184,1.000094,1.005433

## 1. Original Halloween

In [516]:
""" Weights """#KOSPI, -, NASDAQ, S&P, -, -, KOSDAQ
odd_buy = np.array([0.5*1, (1/3*0), 0*1, 0*1, (1/3*0), (1/3*0), 0.5*1]) #11-4
odd_hold = np.array([0.0*1, (1/3*0), 0.0*1, 0.0*1, (1/3*0), (1/3*0), 0.0*1]) #5-10

# odd_buy = np.array([0.2*0.7, (1/3*0.3), 0.3*0.7, 0.2*0.7, (1/3*0.3), (1/3*0.3), 0.3*0.7]) 
# odd_hold = np.array([0.2*0.7, (1/3*0.3), 0.3*0.7, 0.2*0.7, (1/3*0.3), (1/3*0.3), 0.0*0.7])

# odd_buy = np.array([0.0*0.7, (1/3*0.3), 0.0*0.7, 0.0*0.7, (1/3*0.3), (1/3*0.3), 1*0.7]) #11-4
# odd_hold = np.array([0.0*0.7, (1/3*0.3), 0.0*0.7, 0.0*0.7, (1/3*0.3), (1/3*0.3), 0.0*0.7]) #5-10

In [517]:
halloween = stock_data.algo_original_halloween(odd_buy, odd_hold,1000)

Print daily return 2021-12-07 00:00:00
Print daily return 2021-12-08 00:00:00
Print daily return 2021-12-09 00:00:00
Print daily return 2021-12-10 00:00:00
Print daily return 2021-12-13 00:00:00
Print daily return 2021-12-14 00:00:00
Print daily return 2021-12-15 00:00:00
Print daily return 2021-12-16 00:00:00
Print daily return 2021-12-17 00:00:00
Print daily return 2021-12-20 00:00:00
Print daily return 2021-12-21 00:00:00
Print daily return 2021-12-22 00:00:00
Print daily return 2021-12-23 00:00:00
Print daily return 2021-12-24 00:00:00
Print daily return 2021-12-27 00:00:00
Print daily return 2021-12-28 00:00:00
Print daily return 2021-12-29 00:00:00
Print daily return 2021-12-30 00:00:00
Rebalance 2021-12-30 00:00:00
Print daily return 2022-01-04 00:00:00
Print daily return 2022-01-05 00:00:00
Print daily return 2022-01-06 00:00:00
Print daily return 2022-01-07 00:00:00
Print daily return 2022-01-10 00:00:00
Print daily return 2022-01-11 00:00:00
Print daily return 2022-01-12 00:00:00
Print daily return 2022-01-13 00:00:00
Print daily return 2022-01-14 00:00:00
Print daily return 2022-01-17 00:00:00
Print daily return 2022-01-18 00:00:00
Print daily return 2022-01-19 00:00:00
Print daily return 2022-01-20 00:00:00
Print daily return 2022-01-21 00:00:00
Print daily return 2022-01-24 00:00:00
Print daily return 2022-01-25 00:00:00
Print daily return 2022-01-26 00:00:00
Print daily return 2022-01-27 00:00:00
Print daily return 2022-01-28 00:00:00
Rebalance 2022-01-28 00:00:00
Print daily return 2022-02-03 00:00:00
Print daily return 2022-02-04 00:00:00
Print daily return 2022-02-07 00:00:00
Print daily return 2022-02-08 00:00:00
Print daily return 2022-02-09 00:00:00
Print daily return 2022-02-10 00:00:00
Print daily return 2022-02-11 00:00:00
Print daily return 2022-02-15 00:00:00
Print daily return 2022-02-16 00:00:00
Print daily return 2022-02-17 00:00:00
Print daily return 2022-02-18 00:00:00
Print daily return 2022-02-21 00:00:00
Print daily return 2022-02-22 00:00:00
Print daily return 2022-02-23 00:00:00
Print daily return 2022-02-24 00:00:00
Print daily return 2022-02-25 00:00:00
Print daily return 2022-02-28 00:00:00
Rebalance 2022-02-28 00:00:00
Print daily return 2022-03-02 00:00:00
Print daily return 2022-03-03 00:00:00
Print daily return 2022-03-04 00:00:00
Print daily return 2022-03-07 00:00:00
Print daily return 2022-03-08 00:00:00
Print daily return 2022-03-10 00:00:00
Print daily return 2022-03-11 00:00:00
Print daily return 2022-03-14 00:00:00
Print daily return 2022-03-15 00:00:00
Print daily return 2022-03-16 00:00:00
Print daily return 2022-03-17 00:00:00
Print daily return 2022-03-18 00:00:00
Print daily return 2022-03-21 00:00:00
Print daily return 2022-03-22 00:00:00
Print daily return 2022-03-23 00:00:00
Print daily return 2022-03-24 00:00:00
Print daily return 2022-03-25 00:00:00
Print daily return 2022-03-28 00:00:00
Print daily return 2022-03-29 00:00:00
Print daily return 2022-03-30 00:00:00
Print daily return 2022-03-31 00:00:00
Rebalance 2022-03-31 00:00:00
Print daily return 2022-04-01 00:00:00
Print daily return 2022-04-04 00:00:00
Print daily return 2022-04-05 00:00:00
Print daily return 2022-04-06 00:00:00
Print daily return 2022-04-07 00:00:00
Print daily return 2022-04-08 00:00:00
Print daily return 2022-04-11 00:00:00
Print daily return 2022-04-12 00:00:00
Print daily return 2022-04-13 00:00:00
Print daily return 2022-04-14 00:00:00
Print daily return 2022-04-15 00:00:00
Print daily return 2022-04-18 00:00:00
Print daily return 2022-04-19 00:00:00
Print daily return 2022-04-20 00:00:00
Print daily return 2022-04-21 00:00:00
Print daily return 2022-04-22 00:00:00
Print daily return 2022-04-25 00:00:00
Print daily return 2022-04-26 00:00:00
Print daily return 2022-04-27 00:00:00
Print daily return 2022-04-28 00:00:00
Print daily return 2022-04-29 00:00:00
Rebalance 2022-04-29 00:00:00
Print daily return 2022-05-03 00:00:00
Print daily return 2022-05-04 00:00:00
Print daily return 2022-05-06 00:00:00
Print daily return 2022-05-10 00:00:00
Print daily return 2022-05-11 00:00:00
Print daily return 2022-05-12 00:00:00
Print daily return 2022-05-13 00:00:00
Print daily return 2022-05-16 00:00:00
Print daily return 2022-05-17 00:00:00
Print daily return 2022-05-18 00:00:00
Print daily return 2022-05-19 00:00:00
Print daily return 2022-05-20 00:00:00
Print daily return 2022-05-23 00:00:00
Print daily return 2022-05-24 00:00:00
Print daily return 2022-05-25 00:00:00
Print daily return 2022-05-26 00:00:00
Print daily return 2022-05-27 00:00:00
Print daily return 2022-05-30 00:00:00
Print daily return 2022-05-31 00:00:00
Rebalance 2022-05-31 00:00:00
Print daily return 2022-06-02 00:00:00
Print daily return 2022-06-03 00:00:00
Print daily return 2022-06-07 00:00:00
Print daily return 2022-06-08 00:00:00
Print daily return 2022-06-09 00:00:00
Print daily return 2022-06-10 00:00:00
Print daily return 2022-06-13 00:00:00
Print daily return 2022-06-14 00:00:00
Print daily return 2022-06-15 00:00:00
Print daily return 2022-06-16 00:00:00
Print daily return 2022-06-17 00:00:00
Print daily return 2022-06-20 00:00:00
Print daily return 2022-06-21 00:00:00
Print daily return 2022-06-22 00:00:00
Print daily return 2022-06-23 00:00:00
Print daily return 2022-06-24 00:00:00
Print daily return 2022-06-27 00:00:00
Print daily return 2022-06-28 00:00:00
Print daily return 2022-06-29 00:00:00
Print daily return 2022-06-30 00:00:00
Rebalance 2022-06-30 00:00:00
Print daily return 2022-07-01 00:00:00
Print daily return 2022-07-04 00:00:00
Print daily return 2022-07-05 00:00:00
Print daily return 2022-07-06 00:00:00
Print daily return 2022-07-07 00:00:00
Print daily return 2022-07-08 00:00:00
Print daily return 2022-07-11 00:00:00
Print daily return 2022-07-12 00:00:00
Print daily return 2022-07-13 00:00:00
Print daily return 2022-07-14 00:00:00
Print daily return 2022-07-15 00:00:00
Print daily return 2022-07-18 00:00:00
Print daily return 2022-07-19 00:00:00
Print daily return 2022-07-20 00:00:00
Print daily return 2022-07-21 00:00:00
Print daily return 2022-07-22 00:00:00
Print daily return 2022-07-25 00:00:00
Print daily return 2022-07-26 00:00:00
Print daily return 2022-07-27 00:00:00
Print daily return 2022-07-28 00:00:00
Print daily return 2022-07-29 00:00:00
Rebalance 2022-07-29 00:00:00
Print daily return 2022-08-01 00:00:00
Print daily return 2022-08-02 00:00:00
Print daily return 2022-08-03 00:00:00
Print daily return 2022-08-04 00:00:00
Print daily return 2022-08-05 00:00:00
Print daily return 2022-08-08 00:00:00
Print daily return 2022-08-09 00:00:00
Print daily return 2022-08-10 00:00:00
Print daily return 2022-08-11 00:00:00
Print daily return 2022-08-12 00:00:00
Print daily return 2022-08-16 00:00:00
Print daily return 2022-08-17 00:00:00
Print daily return 2022-08-18 00:00:00
Print daily return 2022-08-19 00:00:00
Print daily return 2022-08-22 00:00:00
Print daily return 2022-08-23 00:00:00
Print daily return 2022-08-24 00:00:00
Print daily return 2022-08-25 00:00:00
Print daily return 2022-08-26 00:00:00
Print daily return 2022-08-29 00:00:00
Print daily return 2022-08-30 00:00:00
Print daily return 2022-08-31 00:00:00
Rebalance 2022-08-31 00:00:00
Print daily return 2022-09-01 00:00:00
Print daily return 2022-09-02 00:00:00
Print daily return 2022-09-05 00:00:00
Print daily return 2022-09-06 00:00:00
Print daily return 2022-09-07 00:00:00
Print daily return 2022-09-08 00:00:00
Print daily return 2022-09-13 00:00:00
Print daily return 2022-09-14 00:00:00
Print daily return 2022-09-15 00:00:00
Print daily return 2022-09-16 00:00:00
Print daily return 2022-09-19 00:00:00
Print daily return 2022-09-20 00:00:00
Print daily return 2022-09-21 00:00:00
Print daily return 2022-09-22 00:00:00
Print daily return 2022-09-23 00:00:00
Print daily return 2022-09-26 00:00:00
Print daily return 2022-09-27 00:00:00
Print daily return 2022-09-28 00:00:00
Print daily return 2022-09-29 00:00:00
Print daily return 2022-09-30 00:00:00
Rebalance 2022-09-30 00:00:00
Print daily return 2022-10-04 00:00:00
Print daily return 2022-10-05 00:00:00
Print daily return 2022-10-06 00:00:00
Print daily return 2022-10-07 00:00:00
Print daily return 2022-10-11 00:00:00
Print daily return 2022-10-12 00:00:00
Print daily return 2022-10-13 00:00:00
Print daily return 2022-10-14 00:00:00
Print daily return 2022-10-17 00:00:00
Print daily return 2022-10-18 00:00:00
Print daily return 2022-10-19 00:00:00
Print daily return 2022-10-20 00:00:00
Print daily return 2022-10-21 00:00:00
Print daily return 2022-10-24 00:00:00
Print daily return 2022-10-25 00:00:00
Print daily return 2022-10-26 00:00:00
Print daily return 2022-10-27 00:00:00
Print daily return 2022-10-28 00:00:00
Print daily return 2022-10-31 00:00:00
Rebalance 2022-10-31 00:00:00
Print daily return 2022-11-01 00:00:00
Print daily return 2022-11-02 00:00:00
Print daily return 2022-11-03 00:00:00
Print daily return 2022-11-04 00:00:00
Print daily return 2022-11-07 00:00:00
Print daily return 2022-11-08 00:00:00
Print daily return 2022-11-09 00:00:00
Print daily return 2022-11-10 00:00:00
Print daily return 2022-11-11 00:00:00
Print daily return 2022-11-14 00:00:00
Print daily return 2022-11-15 00:00:00
Print daily return 2022-11-16 00:00:00
Print daily return 2022-11-17 00:00:00
Print daily return 2022-11-18 00:00:00
Print daily return 2022-11-21 00:00:00
Print daily return 2022-11-22 00:00:00
Print daily return 2022-11-23 00:00:00
Print daily return 2022-11-24 00:00:00
Print daily return 2022-11-25 00:00:00
Print daily return 2022-11-28 00:00:00
Print daily return 2022-11-29 00:00:00
Print daily return 2022-11-30 00:00:00
Rebalance 2022-11-30 00:00:00
Print daily return 2022-12-01 00:00:00
Print daily return 2022-12-02 00:00:00
Print daily return 2022-12-05 00:00:00
Print daily return 2022-12-06 00:00:00
Print daily return 2022-12-07 00:00:00
Print daily return 2022-12-08 00:00:00
Print daily return 2022-12-09 00:00:00
Print daily return 2022-12-12 00:00:00
Print daily return 2022-12-13 00:00:00
Print daily return 2022-12-14 00:00:00
Print daily return 2022-12-15 00:00:00
Print daily return 2022-12-16 00:00:00
Print daily return 2022-12-19 00:00:00
Print daily return 2022-12-20 00:00:00
Print daily return 2022-12-21 00:00:00
Print daily return 2022-12-22 00:00:00
Print daily return 2022-12-23 00:00:00
Print daily return 2022-12-26 00:00:00
Print daily return 2022-12-27 00:00:00
Print daily return 2022-12-28 00:00:00
Print daily return 2022-12-29 00:00:00
Rebalance 2022-12-29 00:00:00
Print daily return 2023-01-02 00:00:00
Print daily return 2023-01-03 00:00:00
Print daily return 2023-01-04 00:00:00
Print daily return 2023-01-05 00:00:00
Print daily return 2023-01-06 00:00:00
Print daily return 2023-01-09 00:00:00
Print daily return 2023-01-10 00:00:00
Print daily return 2023-01-11 00:00:00
Print daily return 2023-01-12 00:00:00
Print daily return 2023-01-13 00:00:00
Print daily return 2023-01-16 00:00:00
Print daily return 2023-01-17 00:00:00
Print daily return 2023-01-18 00:00:00
Print daily return 2023-01-19 00:00:00
Print daily return 2023-01-20 00:00:00
Print daily return 2023-01-25 00:00:00
Print daily return 2023-01-26 00:00:00
Print daily return 2023-01-27 00:00:00
Print daily return 2023-01-30 00:00:00
Print daily return 2023-01-31 00:00:00
Rebalance 2023-01-31 00:00:00
Print daily return 2023-02-01 00:00:00
Print daily return 2023-02-02 00:00:00
Print daily return 2023-02-03 00:00:00
Print daily return 2023-02-06 00:00:00
Print daily return 2023-02-07 00:00:00
Print daily return 2023-02-08 00:00:00
Print daily return 2023-02-09 00:00:00
Print daily return 2023-02-10 00:00:00
Print daily return 2023-02-13 00:00:00
Print daily return 2023-02-14 00:00:00
Print daily return 2023-02-15 00:00:00
Print daily return 2023-02-16 00:00:00
Print daily return 2023-02-17 00:00:00
Print daily return 2023-02-20 00:00:00
Print daily return 2023-02-21 00:00:00
Print daily return 2023-02-22 00:00:00
Print daily return 2023-02-23 00:00:00
Print daily return 2023-02-24 00:00:00
Print daily return 2023-02-27 00:00:00
Print daily return 2023-02-28 00:00:00
Rebalance 2023-02-28 00:00:00
Print daily return 2023-03-02 00:00:00
Print daily return 2023-03-03 00:00:00
Print daily return 2023-03-06 00:00:00
Print daily return 2023-03-07 00:00:00
Print daily return 2023-03-08 00:00:00
Print daily return 2023-03-09 00:00:00
Print daily return 2023-03-10 00:00:00
Print daily return 2023-03-13 00:00:00
Print daily return 2023-03-14 00:00:00
Print daily return 2023-03-15 00:00:00
Print daily return 2023-03-16 00:00:00
Print daily return 2023-03-17 00:00:00
Print daily return 2023-03-20 00:00:00
Print daily return 2023-03-21 00:00:00
Print daily return 2023-03-22 00:00:00
Print daily return 2023-03-23 00:00:00
Print daily return 2023-03-24 00:00:00
Print daily return 2023-03-27 00:00:00
Print daily return 2023-03-28 00:00:00
Print daily return 2023-03-29 00:00:00
Print daily return 2023-03-30 00:00:00
Print daily return 2023-03-31 00:00:00
Rebalance 2023-03-31 00:00:00
Print daily return 2023-04-03 00:00:00
Print daily return 2023-04-04 00:00:00
Print daily return 2023-04-05 00:00:00
Print daily return 2023-04-06 00:00:00
Print daily return 2023-04-07 00:00:00
Print daily return 2023-04-10 00:00:00
Print daily return 2023-04-11 00:00:00
Print daily return 2023-04-12 00:00:00
Print daily return 2023-04-13 00:00:00
Print daily return 2023-04-14 00:00:00
Print daily return 2023-04-17 00:00:00
Print daily return 2023-04-18 00:00:00
Print daily return 2023-04-19 00:00:00
Print daily return 2023-04-20 00:00:00
Print daily return 2023-04-21 00:00:00
Print daily return 2023-04-24 00:00:00
Print daily return 2023-04-25 00:00:00
Print daily return 2023-04-26 00:00:00
Print daily return 2023-04-27 00:00:00
Print daily return 2023-04-28 00:00:00
Rebalance 2023-04-28 00:00:00
Print daily return 2023-05-02 00:00:00
Print daily return 2023-05-03 00:00:00
Print daily return 2023-05-04 00:00:00
Print daily return 2023-05-08 00:00:00
Print daily return 2023-05-09 00:00:00
Print daily return 2023-05-10 00:00:00
Print daily return 2023-05-11 00:00:00
Print daily return 2023-05-12 00:00:00
Print daily return 2023-05-15 00:00:00
Print daily return 2023-05-16 00:00:00
Print daily return 2023-05-17 00:00:00
Print daily return 2023-05-19 00:00:00
Print daily return 2023-05-22 00:00:00
Print daily return 2023-05-23 00:00:00
Print daily return 2023-05-25 00:00:00
Print daily return 2023-05-26 00:00:00
Print daily return 2023-05-30 00:00:00
Print daily return 2023-05-31 00:00:00
Rebalance 2023-05-31 00:00:00
Print daily return 2023-06-01 00:00:00
Print daily return 2023-06-02 00:00:00
Print daily return 2023-06-05 00:00:00
Print daily return 2023-06-07 00:00:00
Print daily return 2023-06-08 00:00:00
Print daily return 2023-06-09 00:00:00
Print daily return 2023-06-12 00:00:00
Print daily return 2023-06-13 00:00:00
Print daily return 2023-06-14 00:00:00
Print daily return 2023-06-15 00:00:00
Print daily return 2023-06-16 00:00:00
Print daily return 2023-06-19 00:00:00
Print daily return 2023-06-20 00:00:00
Print daily return 2023-06-21 00:00:00
Print daily return 2023-06-22 00:00:00
Print daily return 2023-06-23 00:00:00
Print daily return 2023-06-26 00:00:00
Print daily return 2023-06-27 00:00:00
Print daily return 2023-06-28 00:00:00
Print daily return 2023-06-29 00:00:00
Print daily return 2023-06-30 00:00:00
Rebalance 2023-06-30 00:00:00
Print daily return 2023-07-07 00:00:00
Print daily return 2023-07-10 00:00:00
Print daily return 2023-07-14 00:00:00
Print daily return 2023-07-17 00:00:00
Print daily return 2023-07-19 00:00:00
Print daily return 2023-07-20 00:00:00
Print daily return 2023-07-21 00:00:00
Print daily return 2023-07-24 00:00:00
Print daily return 2023-07-26 00:00:00
Print daily return 2023-07-28 00:00:00
Rebalance 2023-07-28 00:00:00
Print daily return 2023-08-03 00:00:00
Print daily return 2023-08-04 00:00:00
Print daily return 2023-08-07 00:00:00
Print daily return 2023-08-08 00:00:00
Print daily return 2023-08-09 00:00:00
Print daily return 2023-08-10 00:00:00
Print daily return 2023-08-11 00:00:00
Print daily return 2023-08-14 00:00:00
Print daily return 2023-08-16 00:00:00
Print daily return 2023-08-17 00:00:00
Print daily return 2023-08-18 00:00:00
Print daily return 2023-08-21 00:00:00
Print daily return 2023-08-22 00:00:00
Print daily return 2023-08-23 00:00:00
Print daily return 2023-08-24 00:00:00
Print daily return 2023-08-25 00:00:00
Print daily return 2023-08-28 00:00:00
Print daily return 2023-08-29 00:00:00
Print daily return 2023-08-30 00:00:00
Print daily return 2023-08-31 00:00:00
Rebalance 2023-08-31 00:00:00
Print daily return 2023-09-01 00:00:00
Print daily return 2023-09-04 00:00:00
Print daily return 2023-09-05 00:00:00
Print daily return 2023-09-06 00:00:00
Print daily return 2023-09-07 00:00:00
Print daily return 2023-09-08 00:00:00
Print daily return 2023-09-11 00:00:00
Print daily return 2023-09-12 00:00:00
Print daily return 2023-09-13 00:00:00
Print daily return 2023-09-14 00:00:00
Print daily return 2023-09-15 00:00:00
Print daily return 2023-09-18 00:00:00
Print daily return 2023-09-19 00:00:00
Print daily return 2023-09-20 00:00:00
Print daily return 2023-09-21 00:00:00
Print daily return 2023-09-22 00:00:00
Print daily return 2023-09-25 00:00:00
Print daily return 2023-09-26 00:00:00
Print daily return 2023-09-27 00:00:00
Rebalance 2023-09-27 00:00:00
Print daily return 2023-10-04 00:00:00
Print daily return 2023-10-05 00:00:00
Print daily return 2023-10-06 00:00:00
Print daily return 2023-10-10 00:00:00
Print daily return 2023-10-11 00:00:00
Print daily return 2023-10-12 00:00:00
Print daily return 2023-10-13 00:00:00
Print daily return 2023-10-16 00:00:00
Print daily return 2023-10-17 00:00:00
Print daily return 2023-10-18 00:00:00
Print daily return 2023-10-19 00:00:00
Print daily return 2023-10-20 00:00:00
Print daily return 2023-10-23 00:00:00
Print daily return 2023-10-24 00:00:00
Print daily return 2023-10-25 00:00:00
Print daily return 2023-10-26 00:00:00
Print daily return 2023-10-27 00:00:00
Print daily return 2023-10-30 00:00:00
Print daily return 2023-10-31 00:00:00
Rebalance 2023-10-31 00:00:00
Print daily return 2023-11-01 00:00:00
Print daily return 2023-11-02 00:00:00
Print daily return 2023-11-03 00:00:00
Print daily return 2023-11-06 00:00:00
Print daily return 2023-11-07 00:00:00
Print daily return 2023-11-08 00:00:00
Print daily return 2023-11-09 00:00:00
Print daily return 2023-11-10 00:00:00
Print daily return 2023-11-13 00:00:00
Print daily return 2023-11-14 00:00:00
Print daily return 2023-11-15 00:00:00
Print daily return 2023-11-16 00:00:00
Print daily return 2023-11-17 00:00:00
Print daily return 2023-11-20 00:00:00
Print daily return 2023-11-21 00:00:00
Print daily return 2023-11-22 00:00:00
Print daily return 2023-11-23 00:00:00
Print daily return 2023-11-24 00:00:00
Print daily return 2023-11-27 00:00:00
Print daily return 2023-11-28 00:00:00
Print daily return 2023-11-29 00:00:00
Print daily return 2023-11-30 00:00:00
Rebalance 2023-11-30 00:00:00
Print daily return 2023-12-01 00:00:00
Print daily return 2023-12-04 00:00:00
Print daily return 2023-12-05 00:00:00
Print daily return 2023-12-06 00:00:00
Print daily return 2023-12-07 00:00:00
Print daily return 2023-12-08 00:00:00
Print daily return 2023-12-11 00:00:00
Print daily return 2023-12-12 00:00:00
Print daily return 2023-12-13 00:00:00
Print daily return 2023-12-14 00:00:00
Print daily return 2023-12-15 00:00:00
Print daily return 2023-12-18 00:00:00
Print daily return 2023-12-19 00:00:00
Print daily return 2023-12-20 00:00:00
Print daily return 2023-12-21 00:00:00
Print daily return 2023-12-22 00:00:00
Print daily return 2023-12-26 00:00:00
Print daily return 2023-12-27 00:00:00
Print daily return 2023-12-28 00:00:00
Rebalance 2023-12-28 00:00:00
Print daily return 2024-01-02 00:00:00
Print daily return 2024-01-03 00:00:00
Print daily return 2024-01-04 00:00:00

In [518]:
stock_data.results()[0]

Ticker,069500.KS mkt val,114260.KS mkt val,133690.KS mkt val,143850.KS mkt val,153130.KS mkt val,157450.KS mkt val,229200.KS mkt val,cash_rem,port_val,strat
Date,,,,,,,,,,
2021-12-06,500.000000,0.0,0.0,0.0,0.0,0.0,500.000000,0.0,1000.000000,aggressive
2021-12-07,504.134334,0.0,0.0,0.0,0.0,0.0,503.942407,0.0,1008.076741,aggressive
2021-12-08,506.360514,0.0,0.0,0.0,0.0,0.0,510.113130,0.0,1016.473644,aggressive
2021-12-09,507.887037,0.0,0.0,0.0,0.0,0.0,518.683579,0.0,1026.570616,aggressive
2021-12-10,505.088411,0.0,0.0,0.0,0.0,0.0,508.399040,0.0,1013.487451,aggressive
...,...,...,...,...,...,...,...,...,...,...
2024-02-19,614.841928,0.0,0.0,0.0,0.0,0.0,623.924046,0.0,1238.765974,aggressive
2024-02-20,607.643366,0.0,0.0,0.0,0.0,0.0,628.762452,0.0,1236.405818,aggressive
2024-02-21,606.288342,0.0,0.0,0.0,0.0,0.0,629.684054,0.0,1235.972396,aggressive
2024-02-22,609.421834,0.0,0.0,0.0,0.0,0.0,634.292060,0.0,1243.713894,aggressive
2024-02-23,611.284992,0.0,0.0,0.0,0.0,0.0,636.135262,0.0,1247.420254,aggressive

In [519]:
stock_data.results()[1]

Ticker,069500.KS mkt val,114260.KS mkt val,133690.KS mkt val,143850.KS mkt val,153130.KS mkt val,157450.KS mkt val,229200.KS mkt val,cash_rem,port_val,strat
Date,,,,,,,,,,
2021-12-06,0.500000,0.0,0.0,0.0,0.0,0.0,0.500000,0.0,1.0,aggressive
2021-12-07,0.500095,0.0,0.0,0.0,0.0,0.0,0.499905,0.0,1.0,aggressive
2021-12-08,0.498154,0.0,0.0,0.0,0.0,0.0,0.501846,0.0,1.0,aggressive
2021-12-09,0.494741,0.0,0.0,0.0,0.0,0.0,0.505259,0.0,1.0,aggressive
2021-12-10,0.498367,0.0,0.0,0.0,0.0,0.0,0.501633,0.0,1.0,aggressive
...,...,...,...,...,...,...,...,...,...,...
2024-02-19,0.496334,0.0,0.0,0.0,0.0,0.0,0.503666,0.0,1.0,aggressive
2024-02-20,0.491459,0.0,0.0,0.0,0.0,0.0,0.508541,0.0,1.0,aggressive
2024-02-21,0.490536,0.0,0.0,0.0,0.0,0.0,0.509464,0.0,1.0,aggressive
2024-02-22,0.490002,0.0,0.0,0.0,0.0,0.0,0.509998,0.0,1.0,aggressive
2024-02-23,0.490039,0.0,0.0,0.0,0.0,0.0,0.509961,0.0,1.0,aggressive

In [520]:
# 1. 일별수익률추이
daily_ret = stock_data.daily_ret()

c:\Users\kango\Desktop\cqralgo\cqrsite\portfolio\utilis\class_trial.py:437: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  report['누적수익률'] = self.result['port_val']/self.result['port_val'][0]-1

In [521]:
daily_ret

Ticker,069500.KS mkt val,114260.KS mkt val,133690.KS mkt val,143850.KS mkt val,153130.KS mkt val,157450.KS mkt val,229200.KS mkt val,cash_rem,port_val,일별수익률,누적수익률
Date,,,,,,,,,,,
2021-12-06,500.000000,0.0,0.0,0.0,0.0,0.0,500.000000,0.0,1000.000000,0.000000,0.000000
2021-12-07,504.134334,0.0,0.0,0.0,0.0,0.0,503.942407,0.0,1008.076741,0.008077,0.008077
2021-12-08,506.360514,0.0,0.0,0.0,0.0,0.0,510.113130,0.0,1016.473644,0.008330,0.016474
2021-12-09,507.887037,0.0,0.0,0.0,0.0,0.0,518.683579,0.0,1026.570616,0.009933,0.026571
2021-12-10,505.088411,0.0,0.0,0.0,0.0,0.0,508.399040,0.0,1013.487451,-0.012745,0.013487
...,...,...,...,...,...,...,...,...,...,...,...
2024-02-19,614.841928,0.0,0.0,0.0,0.0,0.0,623.924046,0.0,1238.765974,0.008661,0.238766
2024-02-20,607.643366,0.0,0.0,0.0,0.0,0.0,628.762452,0.0,1236.405818,-0.001905,0.236406
2024-02-21,606.288342,0.0,0.0,0.0,0.0,0.0,629.684054,0.0,1235.972396,-0.000351,0.235972
2024-02-22,609.421834,0.0,0.0,0.0,0.0,0.0,634.292060,0.0,1243.713894,0.006263,0.243714
2024-02-23,611.284992,0.0,0.0,0.0,0.0,0.0,636.135262,0.0,1247.420254,0.002980,0.247420

In [162]:
#daily_ret.loc['2023-06-01':'2023-08-01']
#filtered_df = df[(df['Date'] >= '2023-04-01') & (df['Date'] <='2023-06-01')]

____

## 수익률 테이블

In [ ]:
import pandas as pd

In [ ]:
daily_ret.iloc[-1,:]

Ticker
069500.KS mkt val     575.837571
114260.KS mkt val     154.014240
133690.KS mkt val       0.000000
143850.KS mkt val       0.000000
153130.KS mkt val     154.484967
157450.KS mkt val     154.542497
229200.KS mkt val     599.246815
cash_rem                0.000000
port_val             1638.126091
일별수익률                   0.002029
누적수익률                   0.638126
Name: 2024-02-23 00:00:00, dtype: float64

In [ ]:
refresh = pd.DataFrame(daily_ret.iloc[-1,:]).T

In [ ]:
refresh['일별수익률']

2022-12-29   -0.012548
Name: 일별수익률, dtype: float64

In [ ]:
# Method 2: 
daily_ret.iloc[-1,:]['일별수익률']

-0.012547944740104455

---

In [ ]:
# 2. 월별수익률추이
monthly_ret = stock_data.monthly_ret()
monthly_ret

c:\Users\ewp\Desktop\mySite\cra_backtest\class_trial.py:449: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  self.report2['누적수익률'] = self.report2['port_val']/self.report2['port_val'][0]-1

,069500.KS mkt val,114260.KS mkt val,133690.KS mkt val,143850.KS mkt val,153130.KS mkt val,157450.KS mkt val,229200.KS mkt val,cash_rem,port_val,월별수익률,누적수익률
Date,,,,,,,,,,,
2015-10-01,210.000000,100.000000,0.0,0.0,100.000000,100.000000,280.000000,2.100000e+02,1000.000000,0.000000,0.000000
2015-10-30,282.094160,100.747914,0.0,0.0,100.747914,100.747914,423.141240,1.136868e-13,1007.479144,0.007479,0.007479
2015-11-30,283.931849,101.404232,0.0,0.0,101.404232,101.404232,425.897773,1.136868e-13,1014.042317,0.006514,0.014042
2015-12-30,282.948921,101.053186,0.0,0.0,101.053186,101.053186,424.423381,1.136868e-13,1010.531860,-0.003462,0.010532
2016-01-29,283.303901,101.179965,0.0,0.0,101.179965,101.179965,424.955851,0.000000e+00,1011.799646,0.001255,0.011800
...,...,...,...,...,...,...,...,...,...,...,...
2022-08-31,252.956669,120.455557,0.0,0.0,120.455557,120.455557,337.275559,2.529567e+02,1204.555568,-0.002399,0.204556
2022-09-30,234.696447,111.760213,0.0,0.0,111.760213,111.760213,312.928596,2.346964e+02,1117.602129,-0.072187,0.117602
2022-10-31,321.618976,114.863920,0.0,0.0,114.863920,114.863920,482.428465,0.000000e+00,1148.639201,0.027771,0.148639
2022-11-30,332.646376,118.802277,0.0,0.0,118.802277,118.802277,498.969564,2.273737e-13,1188.022772,0.034287,0.188023
2022-12-29,306.926563,118.623469,0.0,0.0,119.150086,119.123301,465.866014,2.273737e-13,1129.689433,-0.049101,0.129689

In [ ]:
daily_ret.iloc[-50:,:]

,069500.KS mkt val,114260.KS mkt val,133690.KS mkt val,143850.KS mkt val,153130.KS mkt val,157450.KS mkt val,229200.KS mkt val,cash_rem,port_val,일별수익률,누적수익률
Date,,,,,,,,,,,
2022-10-21,240.589797,110.769574,0.0,0.0,111.921817,111.870452,313.256786,2.346964e+02,1123.104873,-0.001027,0.123105
2022-10-24,242.830930,111.487282,0.0,0.0,111.905657,111.875964,323.922941,2.346964e+02,1136.719221,0.012122,0.136719
2022-10-25,243.204453,111.820864,0.0,0.0,111.905657,111.875964,324.251131,2.346964e+02,1137.754515,0.000911,0.137755
2022-10-26,244.864551,111.911841,0.0,0.0,111.905657,111.881476,322.281994,2.346964e+02,1137.541966,-0.000187,0.137542
2022-10-27,249.139305,112.023035,0.0,0.0,111.927204,111.909035,329.502161,2.346964e+02,1149.197188,0.010246,0.149197
2022-10-28,245.072064,112.184772,0.0,0.0,111.916430,111.914547,324.907509,2.346964e+02,1140.691770,-0.007401,0.140692
2022-10-31,321.618976,114.863920,0.0,0.0,114.863920,114.863920,482.428465,0.000000e+00,1148.639201,0.006967,0.148639
2022-11-01,326.502562,115.247387,0.0,0.0,114.858392,114.880891,483.630329,0.000000e+00,1155.119561,0.005642,0.155120
2022-11-02,325.912238,115.205931,0.0,0.0,114.858392,114.880891,480.265108,0.000000e+00,1151.122561,-0.003460,0.151123
2022-11-03,324.087602,114.967560,0.0,0.0,114.863920,114.886548,473.053920,0.000000e+00,1141.859550,-0.008047,0.141860
2022-11-04,326.931888,115.309571,0.0,0.0,114.863920,114.892205,472.573175,0.000000e+00,1144.570758,0.002374,0.144571
2022-11-07,330.420163,114.967560,0.0,0.0,114.891561,114.903519,477.140260,0.000000e+00,1152.323063,0.006773,0.152323
2022-11-08,335.196417,114.936468,0.0,0.0,114.886033,114.920489,488.678161,0.000000e+00,1168.617568,0.014141,0.168618
2022-11-09,338.523695,115.216295,0.0,0.0,114.886033,114.920489,486.995550,0.000000e+00,1170.542063,0.001647,0.170542
2022-11-10,334.284099,115.496123,0.0,0.0,114.930258,114.954431,480.024735,0.000000e+00,1159.689646,-0.009271,0.159690
2022-11-11,347.700542,116.117961,0.0,0.0,114.957899,114.982716,507.667622,0.000000e+00,1201.426739,0.035990,0.201427
2022-11-14,345.500245,116.252693,0.0,0.0,114.991068,114.977059,501.177553,0.000000e+00,1192.898617,-0.007098,0.192899
2022-11-15,346.466229,116.491064,0.0,0.0,114.996596,114.982716,516.801793,0.000000e+00,1209.738398,0.014117,0.209738
2022-11-16,345.822240,116.180145,0.0,0.0,115.018708,115.005343,514.638437,0.000000e+00,1206.664873,-0.002541,0.206665
2022-11-17,341.260649,116.511792,0.0,0.0,115.029765,115.016657,508.629114,0.000000e+00,1196.447977,-0.008467,0.196448
2022-11-18,340.509328,116.231965,0.0,0.0,115.040821,115.027971,502.619790,0.000000e+00,1189.429876,-0.005866,0.189430
2022-11-21,337.879706,116.428880,0.0,0.0,115.057405,115.056256,491.803009,0.000000e+00,1176.225256,-0.011102,0.176225
2022-11-22,335.464746,116.449608,0.0,0.0,115.057405,115.056256,486.034059,0.000000e+00,1168.062074,-0.006940,0.168062
2022-11-23,337.718708,116.345968,0.0,0.0,115.068462,115.067570,497.571959,0.000000e+00,1181.772667,0.011738,0.181773
2022-11-24,340.884989,116.895259,0.0,0.0,115.096102,115.095854,505.985011,0.000000e+00,1193.957216,0.010310,0.193957
2022-11-25,339.489679,116.926351,0.0,0.0,115.151384,115.112825,499.735315,0.000000e+00,1186.415554,-0.006317,0.186416
2022-11-28,335.357414,117.009263,0.0,0.0,115.184553,115.135453,487.476296,0.000000e+00,1170.162979,-0.013699,0.170163
2022-11-29,339.167684,116.915987,0.0,0.0,115.195609,115.141110,497.091213,0.000000e+00,1183.511603,0.011407,0.183512
2022-11-30,332.646376,118.802277,0.0,0.0,118.802277,118.802277,498.969564,2.273737e-13,1188.022772,0.003812,0.188023
2022-12-01,334.616846,118.812795,0.0,0.0,118.842190,118.843135,510.084625,2.273737e-13,1201.199590,0.011091,0.201200
2022-12-02,327.149803,118.802277,0.0,0.0,118.887804,118.854808,498.969564,2.273737e-13,1182.664257,-0.015431,0.182664
2022-12-05,326.112714,118.907458,0.0,0.0,118.916313,118.872319,502.110777,2.273737e-13,1184.919581,0.001907,0.184920
2022-12-06,321.964357,118.812795,0.0,0.0,118.922015,118.878156,492.445507,2.273737e-13,1171.022829,-0.011728,0.171023
2022-12-07,320.149451,118.812795,0.0,0.0,118.944822,118.883992,490.029189,2.273737e-13,1166.820250,-0.003589,0.166820
2022-12-08,320.149451,118.875904,0.0,0.0,118.956225,118.924850,490.512453,2.273737e-13,1167.418883,0.000513,0.167419
2022-12-09,323.882972,118.781241,0.0,0.0,118.956225,118.936524,495.828351,2.273737e-13,1176.385313,0.007681,0.176385
2022-12-12,321.860648,118.949531,0.0,0.0,118.961927,118.948197,489.545926,2.273737e-13,1168.266229,-0.006902,0.168266
2022-12-13,321.601376,118.875904,0.0,0.0,118.979032,118.948197,490.995716,2.273737e-13,1169.400226,0.000971,0.169400
2022-12-14,325.231188,119.191448,0.0,0.0,118.979032,118.959871,502.110777,2.273737e-13,1184.472316,0.012889,0.184472
2022-12-15,319.838324,119.328184,0.0,0.0,119.024647,118.989055,493.170402,2.273737e-13,1170.350611,-0.011922,0.170351
2022-12-16,318.334545,119.307147,0.0,0.0,119.030348,119.006565,486.887977,2.273737e-13,1162.566582,-0.006651,0.162567
2022-12-19,318.386399,119.296629,0.0,0.0,119.036050,119.012402,487.612872,2.273737e-13,1163.344353,0.000669,0.163344
2022-12-20,315.741821,118.781241,0.0,0.0,119.036050,119.018239,477.947602,2.273737e-13,1150.524953,-0.011019,0.150525
2022-12-21,314.964004,119.012640,0.0,0.0,119.036050,119.018239,480.363919,2.273737e-13,1152.394853,0.001625,0.152395
2022-12-22,319.060507,119.170412,0.0,0.0,119.041752,119.041586,492.203875,2.273737e-13,1168.518132,0.013991,0.168518
2022-12-23,313.563934,119.065230,0.0,0.0,119.075963,119.064933,472.631703,2.273737e-13,1143.401764,-0.021494,0.143402
2022-12-26,314.030624,119.002122,0.0,0.0,119.075963,119.064933,481.572078,2.273737e-13,1152.745720,0.008172,0.152746
2022-12-27,316.260366,118.833832,0.0,0.0,119.075963,119.076607,488.579399,2.273737e-13,1161.826166,0.007877,0.161826
2022-12-28,312.526845,118.697096,0.0,0.0,119.138682,119.117465,474.564757,2.273737e-13,1144.044845,-0.015305,0.144045
2022-12-29,306.926563,118.623469,0.0,0.0,119.150086,119.123301,465.866014,2.273737e-13,1129.689433,-0.012548,0.129689

In [ ]:
# 3. 자산별투자비중추이
port_weights = stock_data.portfolio_by_asset_class()

c:\Users\ewp\Desktop\mySite\cra_backtest\class_trial.py:469: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  self.X = asset_perc.applymap(self.to_percentage)

In [ ]:
port_weights[0]

0.46467151638788884

In [ ]:
port_weights[1]

                 5       3      2       1       0    total  위험자산비중  rebal
Date
2015-10-01  28.00%  21.00%  0.00%  30.00%  21.00%  100.00%  28.00%   True
2015-10-02  28.13%  20.87%  0.00%  30.00%  21.00%  100.00%  28.13%  False
2015-10-05  28.29%  20.83%  0.00%  29.93%  20.95%  100.00%  28.29%  False
2015-10-06  28.12%  21.02%  0.00%  29.92%  20.94%  100.00%  28.12%  False
2015-10-07  27.59%  21.41%  0.00%  30.00%  21.00%  100.00%  27.59%  False
...            ...     ...    ...     ...     ...      ...     ...    ...
2022-12-23  41.34%  27.42%  0.00%  31.24%   0.00%  100.00%  41.34%  False
2022-12-26  41.78%  27.24%  0.00%  30.98%   0.00%  100.00%  41.78%  False
2022-12-27  42.05%  27.22%  0.00%  30.73%   0.00%  100.00%  42.05%  False
2022-12-28  41.48%  27.32%  0.00%  31.20%   0.00%  100.00%  41.48%  False
2022-12-29  41.24%  27.17%  0.00%  31.59%   0.00%  100.00%  41.24%  False

[1771 rows x 8 columns]

In [ ]:
y = port_weights[1]

In [ ]:
y.iloc[:,:5].max()

5    46.47%
3    30.29%
2     0.00%
1    36.10%
0    22.92%
dtype: object

In [ ]:
# 4. 종목별투자비중추이
stock_data.portfolio_by_ind_assets()

c:\Users\ewp\Desktop\mySite\cra_backtest\class_trial.py:475: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  self.X1 = self.res_pct.iloc[:,:-1].applymap(self.to_percentage)

,069500.KS mkt val,114260.KS mkt val,133690.KS mkt val,143850.KS mkt val,153130.KS mkt val,157450.KS mkt val,229200.KS mkt val,cash_rem,port_val
Date,,,,,,,,,
2015-10-01,21.00%,10.00%,0.00%,0.00%,10.00%,10.00%,28.00%,21.00%,100.00%
2015-10-02,20.87%,10.00%,0.00%,0.00%,10.00%,10.00%,28.13%,21.00%,100.00%
2015-10-05,20.83%,9.98%,0.00%,0.00%,9.97%,9.97%,28.29%,20.95%,100.00%
2015-10-06,21.02%,9.97%,0.00%,0.00%,9.97%,9.97%,28.12%,20.94%,100.00%
2015-10-07,21.41%,10.00%,0.00%,0.00%,10.00%,10.00%,27.59%,21.00%,100.00%
...,...,...,...,...,...,...,...,...,...
2022-12-23,27.42%,10.41%,0.00%,0.00%,10.41%,10.41%,41.34%,0.00%,100.00%
2022-12-26,27.24%,10.32%,0.00%,0.00%,10.33%,10.33%,41.78%,0.00%,100.00%
2022-12-27,27.22%,10.23%,0.00%,0.00%,10.25%,10.25%,42.05%,0.00%,100.00%
2022-12-28,27.32%,10.38%,0.00%,0.00%,10.41%,10.41%,41.48%,0.00%,100.00%
2022-12-29,27.17%,10.50%,0.00%,0.00%,10.55%,10.54%,41.24%,0.00%,100.00%

In [ ]:
# 5. 리밸런싱발생내역
stock_data.rebalance_history()

                 5       3      2       1       0    total  위험자산비중  rebal
Date
2015-10-01  28.00%  21.00%  0.00%  30.00%  21.00%  100.00%  28.00%   True
2015-10-30  42.00%  28.00%  0.00%  30.00%   0.00%  100.00%  42.00%   True
2015-11-30  42.00%  28.00%  0.00%  30.00%   0.00%  100.00%  42.00%   True
2015-12-30  42.00%  28.00%  0.00%  30.00%   0.00%  100.00%  42.00%   True
2016-01-29  42.00%  28.00%  0.00%  30.00%   0.00%  100.00%  42.00%   True
...            ...     ...    ...     ...     ...      ...     ...    ...
2022-07-29  28.00%  21.00%  0.00%  30.00%  21.00%  100.00%  28.00%   True
2022-08-31  28.00%  21.00%  0.00%  30.00%  21.00%  100.00%  28.00%   True
2022-09-30  28.00%  21.00%  0.00%  30.00%  21.00%  100.00%  28.00%   True
2022-10-31  42.00%  28.00%  0.00%  30.00%   0.00%  100.00%  42.00%   True
2022-11-30  42.00%  28.00%  0.00%  30.00%   0.00%  100.00%  42.00%   True

[87 rows x 8 columns]

## 2. Adjusted Halloween

In [567]:
""" Weights """
#KOSPI, -, NASDAQ, S&P, -, -, KOSDAQ
odd_stock_w = 1
odd_bond_w = 0
even_stock_w = 1
even_bond_w = 0
even_passive_stock_w = 1
even_passive_bond_w = 0

In [568]:
odd_buy = np.array([0.4*odd_stock_w, (1/3*odd_bond_w), 0.0*odd_stock_w, 0.0*odd_stock_w, (1/3*odd_bond_w), (1/3*odd_bond_w), 0.6*odd_stock_w])          # Even 11 - Odd 4. Active
odd_hold = np.array([0.0*odd_stock_w, (1/3*odd_bond_w), 0.5*odd_stock_w, 0.5*odd_stock_w, (1/3*odd_bond_w), (1/3*odd_bond_w), 0.0*odd_stock_w])         # Odd 5 - Odd 10. 
even_buy = np.array([0.5*even_stock_w, (1/3*even_bond_w), 0.0*even_stock_w, 0.0*even_stock_w, (1/3*even_bond_w), (1/3*even_bond_w), 0.5*even_stock_w])  # Odd 11 - Even 4. NOTE: Here, we shift Kospi weight to Nasdaq instead of S&P 500 to be consistent with our logic that 11-4 should be more aggressive than 5-10. 
even_hold = np.array([0.0*even_passive_stock_w, (1/3*even_passive_bond_w), 0.5*even_passive_stock_w, 0.5*even_passive_stock_w, (1/3*even_passive_bond_w), (1/3*even_passive_bond_w), 0.0*even_passive_stock_w])  # Even 5 - Even 10

In [569]:
halloween_adj = stock_data.algo1(1000,odd_buy,odd_hold,even_buy,even_hold)

In [570]:
stock_data.results()[0]

Ticker,069500.KS mkt val,114260.KS mkt val,133690.KS mkt val,143850.KS mkt val,153130.KS mkt val,157450.KS mkt val,229200.KS mkt val,cash_rem,port_val,strat
Date,,,,,,,,,,
2022-06-02,0.000000,0.0,500.000000,500.000000,0.0,0.0,0.000000,0.0,1000.000000,even passive
2022-06-03,0.000000,0.0,509.311914,509.805956,0.0,0.0,0.000000,0.0,1019.117870,even passive
2022-06-07,0.000000,0.0,500.817458,500.051883,0.0,0.0,0.000000,0.0,1000.869341,even passive
2022-06-08,0.000000,0.0,505.224623,506.122237,0.0,0.0,0.000000,0.0,1011.346860,even passive
2022-06-09,0.000000,0.0,502.807791,500.882017,0.0,0.0,0.000000,0.0,1003.689808,even passive
...,...,...,...,...,...,...,...,...,...,...
2024-02-20,724.975735,0.0,0.000000,0.000000,0.0,0.0,750.172793,0.0,1475.148528,even aggressive
2024-02-21,723.359064,0.0,0.000000,0.000000,0.0,0.0,751.272350,0.0,1474.631414,even aggressive
2024-02-22,727.097615,0.0,0.000000,0.000000,0.0,0.0,756.770135,0.0,1483.867750,even aggressive
2024-02-23,729.320537,0.0,0.000000,0.000000,0.0,0.0,758.969249,0.0,1488.289787,even aggressive
2024-02-26,723.460106,0.0,0.000000,0.000000,0.0,0.0,763.092588,0.0,1486.552694,even aggressive

In [571]:
# 1. 일별수익률추이
daily_ret_dad = stock_data.daily_ret()

c:\Users\kango\Desktop\cqralgo\cqrsite\portfolio\utilis\class_trial.py:437: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  report['누적수익률'] = self.result['port_val']/self.result['port_val'][0]-1

In [572]:
daily_ret_dad

Ticker,069500.KS mkt val,114260.KS mkt val,133690.KS mkt val,143850.KS mkt val,153130.KS mkt val,157450.KS mkt val,229200.KS mkt val,cash_rem,port_val,일별수익률,누적수익률
Date,,,,,,,,,,,
2022-06-02,0.000000,0.0,500.000000,500.000000,0.0,0.0,0.000000,0.0,1000.000000,0.000000,0.000000
2022-06-03,0.000000,0.0,509.311914,509.805956,0.0,0.0,0.000000,0.0,1019.117870,0.019118,0.019118
2022-06-07,0.000000,0.0,500.817458,500.051883,0.0,0.0,0.000000,0.0,1000.869341,-0.017906,0.000869
2022-06-08,0.000000,0.0,505.224623,506.122237,0.0,0.0,0.000000,0.0,1011.346860,0.010468,0.011347
2022-06-09,0.000000,0.0,502.807791,500.882017,0.0,0.0,0.000000,0.0,1003.689808,-0.007571,0.003690
...,...,...,...,...,...,...,...,...,...,...,...
2024-02-20,724.975735,0.0,0.000000,0.000000,0.0,0.0,750.172793,0.0,1475.148528,-0.001905,0.475149
2024-02-21,723.359064,0.0,0.000000,0.000000,0.0,0.0,751.272350,0.0,1474.631414,-0.000351,0.474631
2024-02-22,727.097615,0.0,0.000000,0.000000,0.0,0.0,756.770135,0.0,1483.867750,0.006263,0.483868
2024-02-23,729.320537,0.0,0.000000,0.000000,0.0,0.0,758.969249,0.0,1488.289787,0.002980,0.488290
2024-02-26,723.460106,0.0,0.000000,0.000000,0.0,0.0,763.092588,0.0,1486.552694,-0.001167,0.486553

## 수익률 테이블

## Report

---

In [87]:
%matplotlib inline
import quantstats as qs
import webbrowser

In [457]:
# extend pandas functionality with metrics, etc.
qs.extend_pandas()

In [336]:
qs.reports.html(daily_ret['일별수익률']        # <- Input 일별수익률
                , benchmark="^KS11", output=r'c:\kannie\Halloween_kospi_kosdaq.html', title='Halloween_kospi_kosdaq')
#html_file_path = r"C:\Users\ewp\Desktop\mySite\cra_backtest\Halloween_kospi.html"

# Open the HTML file in the default web browser
#webbrowser.open(html_file_path)

c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:555: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:557: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:433: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:435: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1016: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Weekly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1019: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Monthly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1022: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Quarterly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1025: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Yearly"].ffill(inplace=True)

In [458]:
qs.reports.html(daily_ret_dad['일별수익률']        # <- Input 일별수익률
                , benchmark="^GSPC", output=r'c:\kannie\AdjHalloween_all.html', title='AdjHalloween_all')

c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:555: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:557: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:433: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:435: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1016: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Weekly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1019: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Monthly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1022: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Quarterly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1025: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Yearly"].ffill(inplace=True)

In [101]:
import yfinance as yf
import quantstats as qs

In [244]:
df_KQ11 = yf.download('^KQ11', start='2015-10-1', end='2024-02-26')

c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed

In [496]:
df_KQ11 = yf.download('^KQ11', start='2015-10-1', end='2024-02-26')
df_KQ11 = df_KQ11['Adj Close'].pct_change().dropna()
qs.reports.html(df_KQ11 , output=r'c:\kannie\kosdaq2.html', title='kosdaq')

c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1016: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Weekly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1019: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Monthly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1022: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Quarterly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1025: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Yearly"].ffill(inplace=True)

In [497]:
df_KS11 = yf.download('^KS11', start='2015-10-1', end='2024-02-26')
df_KS11 = df_KS11['Adj Close'].pct_change().dropna()
qs.reports.html(df_KS11 , output=r'c:\kannie\kospi2.html', title='kospi')

c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1016: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Weekly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1019: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Monthly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1022: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Quarterly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1025: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Yearly"].ffill(inplace=True)

In [498]:
# df_KQ11 = yf.download('^KQ11', start='22012-05-16', end='2024-02-25')
# df_KS11 = yf.download('^KS11', start='2012-05-16', end='2024-02-25')
# df_DJI = yf.download('^DJI',start='2012-05-16', end='2024-02-25')
df_GSPC = yf.download('^GSPC',start='2015-10-1', end='2024-02-26')
df_IXIC = yf.download('^IXIC',start='2015-10-1', end='2024-02-26')
#Kosdaq Composite Index (^KQ11)
#KOSPI Composite Index (^KS11)
# Dow Jones Industrial Average (^DJI)
# S&P 500 (^GSPC)
# NASDAQ Composite (^IXIC)

c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed

In [99]:
df

Ticker,Date,end of month,year,month,069500.KS,114260.KS,133690.KS,143850.KS,153130.KS,157450.KS,^KQ11
0,2012-05-16,True,2012,5,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,2012-05-17,True,2012,5,0.999593,1.000280,0.998489,1.001080,1.000298,1.000150,1.006710
2,2012-05-18,True,2012,5,0.967006,1.000841,0.978812,0.974470,1.000050,1.000250,0.958452
3,2012-05-21,True,2012,5,1.010320,0.999066,0.997294,1.001107,1.000149,1.000200,1.000468
4,2012-05-22,True,2012,5,1.017511,1.000841,1.016279,1.013638,1.000099,1.000150,1.027980
...,...,...,...,...,...,...,...,...,...,...,...
2863,2024-02-20,True,2024,2,0.988292,0.999831,0.997679,0.996879,1.000046,1.000000,1.008969
2864,2024-02-21,True,2024,2,0.997770,1.000169,0.989412,0.994901,1.000046,1.000141,0.997576
2865,2024-02-22,True,2024,2,1.005168,1.001943,1.009406,1.010161,1.000460,1.000236,1.006990
2866,2024-02-23,True,2024,2,1.003057,0.998820,1.015736,1.013886,0.999954,1.000094,0.998230
2867,2024-02-26,True,2024,2,0.991965,1.001688,0.995085,0.997191,1.000184,1.000094,0.998653

In [499]:
# df_KQ11 = df_KQ11['Adj Close'].pct_change().dropna()
# df_KS11 = df_KS11['Adj Close'].pct_change().dropna()
# df_DJI = df_DJI['Adj Close'].pct_change().dropna()
df_GSPC = df_GSPC['Adj Close'].pct_change().dropna()
df_IXIC = df_IXIC['Adj Close'].pct_change().dropna()

In [44]:
df_KQ11
df_KS11
df_DJI
df_GSPC
df_IXIC

Date
2015-10-02    0.017441
2015-10-05    0.015608
2015-10-06   -0.006881
2015-10-07    0.009012
2015-10-08    0.004099
                ...
2024-02-16   -0.008206
2024-02-20   -0.009183
2024-02-21   -0.003193
2024-02-22    0.029572
2024-02-23   -0.002793
Name: Adj Close, Length: 2112, dtype: float64

In [500]:
qs.reports.html(df_GSPC , output=r'c:\kannie\sp5002.html', title='sp5002')

qs.reports.html(df_IXIC , output=r'c:\kannie\nasdaq2.html', title='nasdaq2')

c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1016: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Weekly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1019: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Monthly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1022: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Quarterly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1025: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Yearly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1016: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Weekly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1019: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Monthly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1022: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Quarterly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1025: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Yearly"].ffill(inplace=True)

In [48]:

qs.reports.html(df_KS11 , output=r'c:\kannie\kospi.html', title='kospi')
qs.reports.html(df_DJI , output=r'c:\kannie\dji.html', title='dji')
qs.reports.html(df_GSPC , output=r'c:\kannie\sp500.html', title='sp500')
qs.reports.html(df_IXIC , output=r'c:\kannie\nasdaq.html', title='nasdaq')

c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1016: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Weekly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1019: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Monthly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1022: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Quarterly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1025: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Yearly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1016: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Weekly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1019: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Monthly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1022: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Quarterly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1025: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Yearly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1016: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Weekly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1019: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Monthly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1022: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Quarterly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1025: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Yearly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1016: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Weekly"].ffill(inplace=True)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
c:\Users\kango\Desktop\cqralgo\cqrsite\v3121\Lib\site-packages\quantstats\_plotting\core.py:1019: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.
